---
driver_plugin: docker
driver_config:
  require_chef_omnibus: 11.6.0

platforms:
- name: ubuntu-12.10
  driver_config:
    image: ubuntu:12.10
    platform: ubuntu
  run_list:

- name: debian-6.0.7
  driver_config:
    image: tianon/debian:6.0.7
    platform: debian
  run_list:

suites:
- name: default
  run_list:
  - recipe[ript]
  - recipe[minitest-handler]
  attributes:
    ript_keys:

